### ISSUE TITLE
Urgent Consult

### ISSUE THREAD

**Issue by joseliko7** [martindisch/Kantidroid#1]
Error to import:

Error:(51, 32) No resource found that matches the given name (at 'text' with value '@string/motd_email').
C:\Users\Jose\Desktop\Kantidroid-master\app\src\main\res\layout\motd_activity.xml
Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Jose\AppData\Local\Android\sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by martindisch** [comment]
The strings `motd_url`, `url_timetable` and `motd_email` differ for each developer. For example, `motd_email` is the developer's email address, which is displayed somewhere in the app. Because we don't necessarily want to share that information on Github, these strings are placed in creds.xml, which also contains credentials for third-party APIs, and as such is not tracked by Git as explained in the [Readme](https://github.com/martindisch/Kantidroid#credentials). You'll need to create this file for yourself or just add the strings to your existing strings.xml.

**Comment by joseliko7** [comment]
I am learning android, I have 16 years.
I have no idea how to do that.

Can you send me a sample file creds.xml ?

**Comment by martindisch** [comment]
creds.xml is just another file containing strings. So you can either create a file called creds.xml in the same place as your strings.xml (that would be `Kantidroid\app\src\main\res\values`) containing this

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_key">your dropbox app key</string>
    <string name="app_secret">your dropbox app secret</string>
    <string name="app_key_db">db-[your dropbox app key]</string>
    <string name="motd_url">http://www.example.org/motd3.txt</string>
    <string name="url_timetable">http://www.example.org/files/</string>
    <string name="motd_email">youremail@example.org</string>
</resources>
```

or you just add all these strings to your existing strings.xml. Obviously you would need to replace all the URLs and Dropbox credentials with actual values.

However, I would really recommend forking simpler Android apps for learning purposes, as this one has additional layers of complexity (e.g. third-party libraries) that make this project too complex for use as a sample.

**Comment by joseliko7** [comment]
Can I delete the backup dropbox ?
I do not want to make copies dropbox.

How can I remove Dropbox ?

**Comment by martindisch** [comment]
The Dropbox library is included as a *.jar file in the /libs folder. You can remove that, but then you'll get tons of compiler errors because some parts of the app rely on it. You would need to remove those as well. But as stated above, there are better ways to learn coding for Android than trying to get this app to compile.
I'm a bit busy at the moment, so unfortunately this is as much help as I can give you.

**Comment by joseliko7** [comment]
Ok, thanks. 
And excuse what a fool I am...

he he
